"""edição dnv nas variaveis de usuario

Revision ID: f71ff8c9ff0d
Revises: 8dc50d79d47a
Create Date: 2025-08-25 16:03:14.337830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71ff8c9ff0d'
down_revision: Union[str, Sequence[str], None] = '8dc50d79d47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
