"""adição nas variaveis de usuario

Revision ID: ff1b60431eee
Revises: fdf8d89fa796
Create Date: 2025-08-25 00:59:58.506831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1b60431eee'
down_revision: Union[str, Sequence[str], None] = 'fdf8d89fa796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.alter_column('usuarios', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
